server:
  port: 8083

spring:
  application:
    name: auth-service

keycloak:
  url: ${KEYCLOAK_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:demo}
  client-id: ${KEYCLOAK_CLIENT_ID:kong-client}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:kong-client-secret}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME:admin}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

logging:
  level:
    com.demo.authservice: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
