server:
  port: 8082
  servlet:
    context-path: /order

spring:
  application:
    name: order-service

logging:
  level:
    com.demo.orderservice: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
